CLI_LAUNCH_SCRIPT defined automatically if `getCliScript` non-empty
Intersmash/intersmash pull request #36
Opened 2023-04-27 12:10 UTC by jstourac

In case that application doesn't define the `CLI_LAUNCH_SCRIPT` environment property, let's define it automatically. This can prevent somebody to forget to define this variable in server provisioning.

## Description

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] Code contributed by me aligns with current project license: [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0)
 - [x] Pull Request contains a description of the changes
 - [x] Pull Request does not include fixes for multiple issues/topics
 - [x] Code is self-descriptive and/or documented
 - [ ] I have implemented unit tests to cover my changes
 - [x] I tested my code in OpenShift

2023-04-27 19:30 UTC, fabiobrz commented
/retest-required

2023-05-03 09:20 UTC, simkam commented
I guess it should be fixed by https://github.com/Intersmash/intersmash/pull/40

/retest

2023-05-03 09:23 UTC, jstourac commented
@simkam ah, you may be right. It just failed 2 times in the row so I didn't realize it could be intermittent. Anyway, for the retest I should've rebase first :sweat_smile:

2023-05-05 10:20 UTC, fabiobrz requested changes
Hi @jstourac - thanks for this PR!
Changes LGTM, but I'd like to see this conditional logic tested, rather than relying on the case where the environment variable has been added at the application level.
What about removing [this](https://github.com/jstourac/intersmash/blob/cliLaunchScript/testsuite/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/OpenShiftProvisionerTestBase.java#L246) line?

2023-05-10 19:53 UTC, fabiobrz commented
Thanks again @jstourac - merging!

2023-05-10 19:54 UTC, fabiobrz approved these changes

2023-05-10 19:55 UTC, merged